rm thesis.aux
rm thesis.loa
rm thesis.lof
rm thesis.log
rm thesis.toc
rm thesis.pdf
rm thesis.dvi
rm thesis.blg
rm thesis.bbl
rm thesis.lot
rm clojure-lgrind.tex
rm xor-results-lgrind.tex
rm implementation-lgrind.tex
rm texput.log